[Window]
# Initial position (X,Y) to start the program
InitX = 200
InitY = 200

[Tweaks]
# Initial PtrState (0-3) - recommended not to use 1 because thats drag and
# relies on XEvents to reset
InitPtrState = 0
# Initial idle value - recommended to start at ChaseIdleReq for offscreen issues
InitIdle = 600
# Required idle value to start chasing mouse pointer (in ticks)
ChaseIdleReq = 600
# Make animations faster or slower - in delay between ticks
TickDelay = 66666 
