[Window]
# Initial position (X,Y) to start the program
InitX = 200
InitY = 200

[Tweaks]
# Initial PtrState (0-3) - recommended not to use 1 because thats drag and
# relies on XEvents to reset
InitPtrState = 0
# Initial idle value - recommended to start at ChaseIdleReq for offscreen issues
InitIdle = 600
# Required idle value to start chasing mouse pointer (in ticks)
ChaseIdleReq = 600
# Make animations faster or slower - in delay between ticks
TickDelay = 66

# desktop-gremlin-linux 3.x modular properties for
# bounds of textures
[TextureBounds]
# s... is start, and e... is end
ssleep = 0
esleep = 49
sidle = 50
eidle = 109
sclick = 110
eclick = 220
sgrab = 221
egrab = 270
shover = 271
ehover = 359
sintro = 360
eintro = 459
soutro = 460
eoutro = 599
total = 600

